// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: shorturl/v1/shorturl.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the user's name.
type GetShorturlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longurl string `protobuf:"bytes,1,opt,name=longurl,proto3" json:"longurl,omitempty"`
}

func (x *GetShorturlRequest) Reset() {
	*x = GetShorturlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shorturl_v1_shorturl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShorturlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShorturlRequest) ProtoMessage() {}

func (x *GetShorturlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_v1_shorturl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShorturlRequest.ProtoReflect.Descriptor instead.
func (*GetShorturlRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *GetShorturlRequest) GetLongurl() string {
	if x != nil {
		return x.Longurl
	}
	return ""
}

// The response message containing the greetings
type GetShorturlReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Shorturl string `protobuf:"bytes,1,opt,name=shorturl,proto3" json:"shorturl,omitempty"`
}

func (x *GetShorturlReply) Reset() {
	*x = GetShorturlReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shorturl_v1_shorturl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetShorturlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShorturlReply) ProtoMessage() {}

func (x *GetShorturlReply) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_v1_shorturl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShorturlReply.ProtoReflect.Descriptor instead.
func (*GetShorturlReply) Descriptor() ([]byte, []int) {
	return file_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *GetShorturlReply) GetShorturl() string {
	if x != nil {
		return x.Shorturl
	}
	return ""
}

type GetLongurlRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code string `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *GetLongurlRequest) Reset() {
	*x = GetLongurlRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shorturl_v1_shorturl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLongurlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLongurlRequest) ProtoMessage() {}

func (x *GetLongurlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_v1_shorturl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLongurlRequest.ProtoReflect.Descriptor instead.
func (*GetLongurlRequest) Descriptor() ([]byte, []int) {
	return file_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{2}
}

func (x *GetLongurlRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type GetLongurlReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Longurl string `protobuf:"bytes,1,opt,name=longurl,proto3" json:"longurl,omitempty"`
}

func (x *GetLongurlReply) Reset() {
	*x = GetLongurlReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_shorturl_v1_shorturl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLongurlReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLongurlReply) ProtoMessage() {}

func (x *GetLongurlReply) ProtoReflect() protoreflect.Message {
	mi := &file_shorturl_v1_shorturl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLongurlReply.ProtoReflect.Descriptor instead.
func (*GetLongurlReply) Descriptor() ([]byte, []int) {
	return file_shorturl_v1_shorturl_proto_rawDescGZIP(), []int{3}
}

func (x *GetLongurlReply) GetLongurl() string {
	if x != nil {
		return x.Longurl
	}
	return ""
}

var File_shorturl_v1_shorturl_proto protoreflect.FileDescriptor

var file_shorturl_v1_shorturl_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6c, 0x6f, 0x6e, 0x67, 0x75, 0x72, 0x6c, 0x22, 0x2e, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x53, 0x68,
	0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x22, 0x27, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c, 0x6f,
	0x6e, 0x67, 0x75, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x22, 0x2b, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x75, 0x72, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x75, 0x72, 0x6c, 0x32, 0xe5, 0x01,
	0x0a, 0x0f, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x6b, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c,
	0x12, 0x1f, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1c, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x16, 0x3a, 0x01, 0x2a, 0x22, 0x11, 0x2f, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x75, 0x72, 0x6c, 0x12, 0x65,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x75, 0x72, 0x6c, 0x12, 0x1e, 0x2e, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f,
	0x6e, 0x67, 0x75, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f,
	0x6e, 0x67, 0x75, 0x72, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93,
	0x02, 0x13, 0x12, 0x11, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x73, 0x2f, 0x7b,
	0x63, 0x6f, 0x64, 0x65, 0x7d, 0x42, 0x1d, 0x5a, 0x1b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72,
	0x6c, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c, 0x2f, 0x76,
	0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_shorturl_v1_shorturl_proto_rawDescOnce sync.Once
	file_shorturl_v1_shorturl_proto_rawDescData = file_shorturl_v1_shorturl_proto_rawDesc
)

func file_shorturl_v1_shorturl_proto_rawDescGZIP() []byte {
	file_shorturl_v1_shorturl_proto_rawDescOnce.Do(func() {
		file_shorturl_v1_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(file_shorturl_v1_shorturl_proto_rawDescData)
	})
	return file_shorturl_v1_shorturl_proto_rawDescData
}

var file_shorturl_v1_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_shorturl_v1_shorturl_proto_goTypes = []interface{}{
	(*GetShorturlRequest)(nil), // 0: shorturl.v1.GetShorturlRequest
	(*GetShorturlReply)(nil),   // 1: shorturl.v1.GetShorturlReply
	(*GetLongurlRequest)(nil),  // 2: shorturl.v1.GetLongurlRequest
	(*GetLongurlReply)(nil),    // 3: shorturl.v1.GetLongurlReply
}
var file_shorturl_v1_shorturl_proto_depIdxs = []int32{
	0, // 0: shorturl.v1.ShorturlService.GetShorturl:input_type -> shorturl.v1.GetShorturlRequest
	2, // 1: shorturl.v1.ShorturlService.GetLongurl:input_type -> shorturl.v1.GetLongurlRequest
	1, // 2: shorturl.v1.ShorturlService.GetShorturl:output_type -> shorturl.v1.GetShorturlReply
	3, // 3: shorturl.v1.ShorturlService.GetLongurl:output_type -> shorturl.v1.GetLongurlReply
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_shorturl_v1_shorturl_proto_init() }
func file_shorturl_v1_shorturl_proto_init() {
	if File_shorturl_v1_shorturl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_shorturl_v1_shorturl_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShorturlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shorturl_v1_shorturl_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetShorturlReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shorturl_v1_shorturl_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLongurlRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_shorturl_v1_shorturl_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLongurlReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_shorturl_v1_shorturl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shorturl_v1_shorturl_proto_goTypes,
		DependencyIndexes: file_shorturl_v1_shorturl_proto_depIdxs,
		MessageInfos:      file_shorturl_v1_shorturl_proto_msgTypes,
	}.Build()
	File_shorturl_v1_shorturl_proto = out.File
	file_shorturl_v1_shorturl_proto_rawDesc = nil
	file_shorturl_v1_shorturl_proto_goTypes = nil
	file_shorturl_v1_shorturl_proto_depIdxs = nil
}
