// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/flightzw/shorturl/internal/biz"
	"github.com/flightzw/shorturl/internal/conf"
	"github.com/flightzw/shorturl/internal/data"
	"github.com/flightzw/shorturl/internal/server"
	"github.com/flightzw/shorturl/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	client := data.NewRedisClient(confData, logger)
	dataData, cleanup, err := data.NewData(confData, logger, client)
	if err != nil {
		return nil, nil, err
	}
	shorturlRepo := data.NewShorturlMongoRepo(dataData, logger)
	shorturlUsecase := biz.NewShorturlUsecase(shorturlRepo, logger, confData)
	shorturlService := service.NewShorturlService(shorturlUsecase)
	grpcServer := server.NewGRPCServer(confServer, shorturlService, logger)
	httpServer := server.NewHTTPServer(confServer, shorturlService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
